import { NextResponse } from "next/server";
import { isOfficeRole } from "@/lib/auth/roles";
import { getRequestStaff } from "@/lib/auth/session";
import { nowUtcIso } from "@/lib/dates";
import { recordClaimEvent } from "@/lib/db/chronology";
import {
  addDisclosureConcern,
  addImpecuniosityAccount,
  saveFinancialCircumstances,
  saveMitigationStatement,
  setChecklistStatus,
  setImpecuniosityApproval,
} from "@/lib/db/impecuniosity";
import { browserOrigin } from "@/lib/http/browser-origin";

function back(origin: string, claimId: string, error?: string, saved?: string) {
  const url = new URL(`/claims/${claimId}/financial`, origin);
  if (error) url.searchParams.set("error", error);
  else if (saved) url.searchParams.set("saved", saved);
  return NextResponse.redirect(url, 303);
}

export async function POST(request: Request, context: { params: Promise<{ id: string }> }) {
  const { id } = await context.params;
  const origin = browserOrigin(request);
  const staff = await getRequestStaff();
  if (!staff) return NextResponse.redirect(new URL("/login", origin), 303);
  if (!isOfficeRole(staff.role)) return NextResponse.redirect(new URL("/jobs", origin), 303);

  try {
    const form = await request.formData();
    const intent = String(form.get("intent") || "");
    if (intent === "circumstances") {
      saveFinancialCircumstances({
        claimId: id,
        actorId: staff.id,
        employmentStatus: String(form.get("employmentStatus") || ""),
        employmentWords: String(form.get("employmentWords") || ""),
        incomeAsStated: String(form.get("incomeAsStated") || ""),
        benefitsAsStated: String(form.get("benefitsAsStated") || ""),
        abilityToPay: String(form.get("abilityToPay") || ""),
        abilityToPayWords: String(form.get("abilityToPayWords") || ""),
        noBankExplanation: String(form.get("noBankExplanation") || ""),
        correctionReason: String(form.get("correctionReason") || ""),
      });
      recordClaimEvent({
        claimId: id,
        eventType: "other",
        details: "Financial circumstances recorded as a new dated entry. This is not a finding on recoverability.",
        actorId: staff.id,
        occurredAt: nowUtcIso(),
        source: "staff",
      });
      return back(origin, id, undefined, "circumstances");
    }
    if (intent === "account") {
      addImpecuniosityAccount({
        claimId: id,
        actorId: staff.id,
        label: String(form.get("label") || ""),
        kind: String(form.get("kind") || ""),
        notes: String(form.get("notes") || ""),
      });
      recordClaimEvent({
        claimId: id,
        eventType: "other",
        details: "An impecuniosity evidence item was listed. The checklist status was not changed.",
        actorId: staff.id,
        occurredAt: nowUtcIso(),
        source: "staff",
      });
      return back(origin, id, undefined, "account");
    }
    if (intent === "checklist") {
      const status = String(form.get("status") || "");
      setChecklistStatus({ claimId: id, actorId: staff.id, actorRole: staff.role, status });
      recordClaimEvent({
        claimId: id,
        eventType: "other",
        details:
          status === "complete"
            ? "Evidence checklist marked Complete by a handler. This does not mean the charges can be recovered."
            : `Evidence checklist set to ${status.replaceAll("_", " ")} by a handler.`,
        actorId: staff.id,
        occurredAt: nowUtcIso(),
        source: "staff",
      });
      return back(origin, id, undefined, "checklist");
    }
    if (intent === "concern") {
      addDisclosureConcern({
        claimId: id,
        actorId: staff.id,
        actorRole: staff.role,
        body: String(form.get("body") || ""),
      });
      recordClaimEvent({
        claimId: id,
        eventType: "other",
        details: "A handler recorded a disclosure concern. It was not generated by the system.",
        actorId: staff.id,
        occurredAt: nowUtcIso(),
        source: "staff",
      });
      return back(origin, id, undefined, "concern");
    }
    if (intent === "approval") {
      const approved = String(form.get("approved") || "") === "yes";
      setImpecuniosityApproval({ claimId: id, actorId: staff.id, actorRole: staff.role, approved });
      recordClaimEvent({
        claimId: id,
        eventType: "other",
        details: approved
          ? "An authorised user approved relying on impecuniosity. The checklist must also be Complete before a document can rely on it."
          : "An authorised user withdrew approval to rely on impecuniosity.",
        actorId: staff.id,
        occurredAt: nowUtcIso(),
        source: "staff",
      });
      return back(origin, id, undefined, "approval");
    }
    if (intent === "mitigation") {
      saveMitigationStatement({
        claimId: id,
        actorId: staff.id,
        statementOn: String(form.get("statementOn") || ""),
        correctionReason: String(form.get("correctionReason") || ""),
        offerPosition: String(form.get("offerPosition") || ""),
        declinedOfferReason: String(form.get("declinedOfferReason") || ""),
        understandsPersonalLiability: form.get("understandsPersonalLiability") === "1",
        needReason: String(form.get("needReason") || ""),
        ownVehicleUnusable: form.get("ownVehicleUnusable") === "1",
        noOtherVehicle: form.get("noOtherVehicle") === "1",
      });
      recordClaimEvent({
        claimId: id,
        eventType: "other",
        details: "Mitigation statement recorded as a new dated entry. Any earlier statement was kept.",
        actorId: staff.id,
        occurredAt: nowUtcIso(),
        source: "staff",
      });
      return back(origin, id, undefined, "mitigation");
    }
    return back(origin, id, "Choose what to save.");
  } catch (error) {
    const message = error instanceof Error ? error.message : "That could not be saved.";
    return back(origin, id, message);
  }
}
